### ISSUE TITLE
Version TFT

### ISSUE THREAD

**Issue by JeedHome44** [artillery3d/sidewinder-x1-tft-firmware#2]
Bonjour,

Pourquoi le firmware TFT que vous fournissez ici ne ressemble pas à celui d’origine sur ma SW X1 v4?
Pourriez vous mettre à jour votre GitHub pour proposer la dernière version actuelle?

Merci

**Comment by Mactastic1-5** [comment]
> Bonjour,
> 
> Pourquoi le firmware TFT que vous fournissez ici ne ressemble pas à celui d’origine sur ma SW X1 v4?
> Pourriez vous mettre à jour votre GitHub pour proposer la dernière version actuelle?
> 
> Merci

If you bought it from a reseller, they might have changed the appearance of the TFT.
